# Generated by Django 4.0.5 on 2022-07-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
