# Generated by Django 4.0.5 on 2022-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_panier_date_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='ordered',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
